image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cd main && go get -v -t -d ./... && echo building main... && go install .
      cd ../stream && go get -v -t -d ./... && echo building stream... && go install .
      cd ..