image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build Go Apps
    command: |
      ./build.sh
      test $? -eq 0 && exit || echo "Build Failed"
    openMode: split-right

  - name: Terminal
    init: clear
    openMode: split-left