image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build Go Apps
    init: |
      clear
      ./build.sh
      test $? -eq 0 && exit || echo "Build Failed"
    openMode: split-right

  - command: clear
    openMode: split-left