image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terminal
    command: clear
    openMode: split-left

  - name: Build Go Apps
    init: |
      ./build.sh
      test $? -eq 0 && exit || echo "Build Failed"
    openMode: split-right