image:
  file: .gitpod.Dockerfile

tasks:
  - command: clear
    openMode: split-left

  - name: Build Go Apps
    command: |
      clear
      ./build.sh
      test $? -eq 0 && exit || echo "Build Failed"
    openMode: split-right