image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build Go Apps
    command: |
      cd $GITPOD_REPO_ROOT/main && go get -v -t -d ./... && echo building main... && go install .
      cd $GITPOD_REPO_ROOT/main && go get -v -t -d ./... && echo building stream... && go install .
      exit
    openMode: split-right

  - name: Terminal
    init: clear
    openMode: split-left